# GitHub Pages configuration for Katana Extension Site
title: "Katana Chrome Extension"
description: "Enhance your Katana MRP workflow with powerful automation tools"
baseurl: ""
url: ""

# Theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Minima theme settings
minima:
  skin: auto
  social_links:
    github: your-username
    # Add other social links as needed

# Header pages (these will appear in navigation)
header_pages:
  - user-guide.md
  - technical-docs.md
  - version-history.md
  - privacy-policy.md
  - license-info.md

# Include files that start with underscores
include:
  - _pages

# Exclude files from processing
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - INSTRUCTIONS.md
  - CHANGELOG.md
  - PRIVACY.md
  - LICENSE

# SEO settings
author: "Katana Extension Team"
email: your-email@example.com
twitter:
  username: 
facebook:
  app_id: 
  publisher: 

# Social media links (update with your actual profiles)
github_username: your-username 